name: Feature Request
description: Suggest a new feature for the Parental Control Monitor app
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make the app better.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Monitoring capability
        - User interface
        - Telegram integration
        - Device optimization
        - Security/Privacy
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: Problem This Solves
      description: What problem would this feature solve?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: For example, when monitoring...
    validations:
      required: true

  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed Implementation
      description: How do you think this feature should work?
      placeholder: The feature could work by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Essential for my use case
        - Critical - App is incomplete without it
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there any alternative solutions or workarounds you've considered?

  - type: checkboxes
    id: device-compatibility
    attributes:
      label: Device Compatibility
      description: Which devices should this feature support?
      options:
        - label: Huawei Nova 3i (primary target)
        - label: Other Huawei devices
        - label: All Android devices
        - label: Specific Android versions only

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledgments
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested
        - label: This feature request is for legitimate parental control purposes
          required: true
        - label: I understand this is a volunteer-maintained project
