name: Android CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Normalize gradlew (LF, no BOM) and permissions
        run: |
          python3 - <<'PY'
          import codecs
          p = 'gradlew'
          data = open(p, 'rb').read()
          if data.startswith(codecs.BOM_UTF8):
              data = data[len(codecs.BOM_UTF8):]
          data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
          open(p, 'wb').write(data)
          PY
          chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app (assemble APKs and bundles)
        run: |
          cd app
          ../gradlew clean assembleDebug assembleRelease bundleDebug bundleRelease --no-daemon --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-aab
          path: app/build/outputs/bundle/debug/app-debug.aab
          if-no-files-found: ignore

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: ignore
