name: Android Build - Final Fix

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Fix gradlew encoding and permissions
      run: |
        # Remove BOM and fix line endings completely
        sed -i '1s/^\xEF\xBB\xBF//' gradlew
        dos2unix gradlew 2>/dev/null || true
        chmod +x gradlew
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Build Debug APK
      run: |
        ./gradlew :app:assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
