name: Android Build Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        
    - uses: android-actions/setup-android@v3
      
    - name: Fix gradlew
      run: |
        echo "#!/usr/bin/env sh" > gradlew
        echo "" >> gradlew
        echo "DIRNAME=\$(dirname \"\$0\")" >> gradlew
        echo "cd \"\$DIRNAME\"" >> gradlew
        echo "exec java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain \"\$@\"" >> gradlew
        chmod +x gradlew
        
    - uses: gradle/gradle-build-action@v2
        
    - name: Build with detailed output
      run: |
        ./gradlew app:assembleDebug --stacktrace --info --continue
        
    - name: Upload APK on success
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          build/
          app/build/
          **/*.log
