name: Android CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize gradlew (LF, no BOM) and permissions
        run: |
          python3 - <<'PY'
          import codecs
          p = 'gradlew'
          data = open(p, 'rb').read()
          if data.startswith(codecs.BOM_UTF8):
              data = data[len(codecs.BOM_UTF8):]
          data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
          open(p, 'wb').write(data)
          PY
          chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: List projects and tasks (diagnostics)
        run: |
          ./gradlew projects
          ./gradlew tasks --all

      - name: Build app (assemble APKs and bundles)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./gradlew :app:clean :app:assembleDebug :app:assembleRelease :app:bundleDebug :app:bundleRelease --no-daemon --stacktrace

      - name: List outputs for debugging
        if: always()
        run: |
          ls -R app/build || true
          find app/build -type f \( -name "*.apk" -o -name "*.aab" \) -print || true

      - name: Run unit tests (best-effort)
        run: ./gradlew :app:testDebugUnitTest || true

      - name: Upload build outputs (APKs/AABs)
        uses: actions/upload-artifact@v4
        with:
          name: app-build-outputs
          path: app/build/outputs/**
          if-no-files-found: warn
          retention-days: 14
