name: Android Build Ultimate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        
    - uses: android-actions/setup-android@v3
      
    - name: Clean gradlew completely
      run: |
        echo "#!/usr/bin/env sh" > gradlew
        echo "" >> gradlew
        echo "# This is a fresh gradlew script" >> gradlew
        echo "DIRNAME=\$(dirname \"\$0\")" >> gradlew
        echo "cd \"\$DIRNAME\"" >> gradlew
        echo "exec java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain \"\$@\"" >> gradlew
        chmod +x gradlew
        
    - name: List available tasks
      run: ./gradlew tasks --all
        
    - name: Build with explicit module
      run: ./gradlew app:assembleDebug
        
    - uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
