name: Android Build Clean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        
    - uses: android-actions/setup-android@v3
      
    - name: Fix gradlew
      run: |
        sed -i '1s/^\xEF\xBB\xBF//' gradlew
        dos2unix gradlew || true
        chmod +x gradlew
        
    - uses: gradle/gradle-build-action@v2
        
    - name: Build APK
      run: ./gradlew assembleDebug
        
    - uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
