name: Android CI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize gradlew (LF, no BOM) and permissions
        run: |
          python3 - <<'PY'
          import codecs
          p = 'gradlew'
          data = open(p, 'rb').read()
          if data.startswith(codecs.BOM_UTF8):
              data = data[len(codecs.BOM_UTF8):]
          data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
          open(p, 'wb').write(data)
          PY
          chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        continue-on-error: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "platforms;android-33" "build-tools;33.0.2"

      - name: Grant execute permission for gradlew (re-assert)
        run: chmod +x gradlew

      - name: List projects and tasks (diagnostics)
        run: |
          ./gradlew projects | cat
          ./gradlew tasks --all | cat

      - name: Build app (assemble APKs)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        working-directory: app
        run: ../gradlew clean assembleDebug assembleRelease --no-daemon --stacktrace | cat

      - name: List outputs for debugging
        if: always()
        run: |
          ls -R build || true
          find . -type f \( -name "*.apk" -o -name "*.aab" \) -print || true

      - name: Upload build outputs (APKs/AABs)
        uses: actions/upload-artifact@v4
        with:
          name: app-build-outputs
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/**/*.aab
          if-no-files-found: warn
          retention-days: 14
