name: Debug Gradle

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Check gradlew file
      run: |
        ls -la gradlew
        head -5 gradlew
        
    - name: Check wrapper properties
      run: |
        ls -la gradle/wrapper/
        cat gradle/wrapper/gradle-wrapper.properties || echo "Properties file not found"
        
    - name: Try gradle version
      run: |
        ./gradlew --version
        
    - name: List all available tasks
      run: |
        ./gradlew --console=plain tasks --all
