name: Fix Line Endings and Test

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        
    - name: Check and Fix Line Endings
      run: |
        echo "=== Checking gradlew file ==="
        ls -la gradlew
        echo "=== File type ==="
        file gradlew
        echo "=== First few lines ==="
        head -5 gradlew | od -c
        echo "=== Converting line endings ==="
        dos2unix gradlew || true
        echo "=== After conversion ==="
        file gradlew
        
    - name: Make Executable and Test
      run: |
        chmod +x gradlew
        echo "=== Testing version ==="
        ./gradlew --version
        echo "=== Testing tasks ==="
        ./gradlew tasks | head -20
